# Generated by Django 6.0.6 on 2026-07-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profilereport_userblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hidden_by_moderation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
    ]
