# Generated by Django 6.0.6 on 2026-07-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_hidden_by_moderation_profile_moderation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('woman', 'Woman'), ('man', 'Man'), ('non_binary', 'Non-binary'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='interested_in',
            field=models.CharField(blank=True, choices=[('women', 'Women'), ('men', 'Men'), ('everyone', 'Everyone')], max_length=20),
        ),
    ]
