# Generated by Django 6.0.6 on 2026-07-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_photo'),
        ('profiles', '0005_profile_gender_profile_interested_in'),
    ]

    operations = [
    ]
