# Generated by Django 6.0.6 on 2026-07-13 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_merge_20260712_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
