# Generated by Django 6.0.6 on 2026-07-20 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_report_evidence_and_account_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['profile_visible', 'hidden_by_moderation', 'gender', 'interested_in', 'connection_goal', '-updated_at'], name='profiles_discovery_idx'),
        ),
    ]
