# Generated by Django 6.0.6 on 2026-07-06 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_call'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['thread', 'started_at'], name='chat_call_thread__36eccd_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['caller', 'started_at'], name='chat_call_caller__e221c2_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['receiver', 'started_at'], name='chat_call_receive_6f5ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['status'], name='chat_call_status_433baa_idx'),
        ),
        migrations.AddIndex(
            model_name='chatattachment',
            index=models.Index(fields=['attachment_type'], name='chat_chatat_attachm_00bf28_idx'),
        ),
        migrations.AddIndex(
            model_name='chatattachment',
            index=models.Index(fields=['created_at'], name='chat_chatat_created_d03b84_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='chat_chatme_thread__b4c881_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='chat_chatme_sender__1d0b99_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_read'], name='chat_chatme_is_read_24fa80_idx'),
        ),
    ]
