# Generated by Django 6.0.6 on 2026-07-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_callsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatattachment',
            name='attachment_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('audio', 'Voice note')], max_length=10),
        ),
    ]
