# Generated by Django 6.0.6 on 2026-07-09 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatattachment_attachment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.chatmessage'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['thread', 'started_at'], name='chat_callse_thread__ff549f_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['caller', 'started_at'], name='chat_callse_caller__91ab43_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['receiver', 'started_at'], name='chat_callse_receive_223323_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['status'], name='chat_callse_status_23f2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['reply_to'], name='chat_chatme_reply_t_2f798f_idx'),
        ),
    ]
