# Generated by Django 6.0.6 on 2026-07-20 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chatreport_evidence_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['user_one', '-updated_at'], name='chat_thread_user1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['user_two', '-updated_at'], name='chat_thread_user2_idx'),
        ),
    ]
