# Generated by Django 6.0.6 on 2026-06-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['gender', 'interested_in'], name='accounts_cu_gender_91cb1d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['location'], name='accounts_cu_locatio_7d46a9_idx'),
        ),
    ]
