# Generated by Django 6.0.6 on 2026-06-28 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='accounts_cu_email_5ce40b_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='accounts_cu_gender_91cb1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='accounts_cu_locatio_7d46a9_idx',
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='User email address. Used for login.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interested_in',
            field=models.CharField(blank=True, choices=[('male', 'Men'), ('female', 'Women'), ('both', 'Everyone'), ('friends', 'Friends first')], max_length=30),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='allow_messages_from',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='blocked_users',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_visibility',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='show_age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='show_distance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='show_last_active',
        ),
    ]
