# Generated by Django 6.0.6 on 2026-07-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_post_hidden_at_post_hidden_by_post_is_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hidden_by_moderation',
            field=models.BooleanField(default=False),
        ),
    ]
