# Generated by Django 6.0.6 on 2026-07-08 22:03

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_post_hidden_by_moderation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hidden_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hidden_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hidden_by_moderation',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='post',
            name='moderation_note',
        ),
        migrations.RemoveField(
            model_name='postreport',
            name='moderator_note',
        ),
        migrations.RemoveField(
            model_name='postreport',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='postreport',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='postreport',
            name='status',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='edited_at', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='feed/videos/'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='feed.post'),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='reason',
            field=models.CharField(choices=[('other', 'Other'), ('spam', 'Spam'), ('harassment', 'Harassment'), ('impersonation', 'Impersonation'), ('inappropriate', 'Inappropriate content')], default='other', max_length=40),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_post_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
