# Generated by Django 6.0.6 on 2026-06-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gropusermemory',
            name='personality_notes',
        ),
        migrations.AlterField(
            model_name='gropmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20),
        ),
    ]
