# Generated by Django 6.0.6 on 2026-07-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0004_remove_aichatsession_user_heartlymessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartlymessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=20),
        ),
    ]
