# Generated by Django 6.0.6 on 2026-07-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pushsubscription'),
        ('notifications', '0002_remove_notification_notificatio_recipie_a972ce_idx_and_more'),
    ]

    operations = [
    ]
