# Generated by Django 6.0.6 on 2026-07-20 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_merge_20260714_0827'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_resolved', '-created_at'], name='notify_recipient_recent_idx'),
        ),
    ]
